### ISSUE TITLE
Feature checklist

### ISSUE THREAD

**Issue by jb55** [maxogden/standard-format#6]
Since I don't want to spam everyone with issues, I'm going to compile the things to do in this thread

* [x] convert `"` to `'` except when `"` contains a `'`
* [x] spaced infix operators
* [x] end of function, but not eol semicolons. eg: `function() { return 2; }`
* [ ] fix some unnecessary inserted SOL semicolons
* [x] eol semicolons
* if I miss any add a PR and i'll add it here

Some of these edge cases will need some pretty gnarly regex. Perhaps consider an AST parser and pretty printer for `v2.0` or `v3.0`? Also thinking long down the road, perhaps a generic pretty printer based off `eslintrc` options. No idea how hard that would be though.

**Comment by Flet** [comment]
Is there an opposition to using something like [jsfmt](https://github.com/rdio/jsfmt) or [esformatter](https://github.com/millermedeiros/esformatter) to achieve formatting? It could be done simiilar to `standard` itself: by wrapping the command and including a standard rc file to implement the rules.

**Comment by jb55** [comment]
@Flet not all all! It's probably the only way to do it robustly and non-destructively. If there was a PR that called a proper formatter with the right options I think that would be great :+1:

**Comment by maxogden** [comment]
My working theory is that we would need a CST and not an AST to do it non-destructively since ASTs are lossy. To know if it was destructive we would need a good test suite with lots of different non-traditional JS styles in it.

**Comment by Flet** [comment]
Looks like esformatter uses [rocambole](https://github.com/millermedeiros/rocambole) to be non-destructive:

>
Recursively walk and add extra information/helpers to Esprima / Mozilla SpiderMonkey Parser API compatible AST.
>
The main difference between other tools is that it also keeps information about tokens and white spaces and it is meant to be used to transform the tokens and not the string values itself.
>
This library is specially useful for non-destructive AST manipulation.

Pretty neat:
>
## Extra Tokens
>
Besides all the regular tokens returned by `esprima` we also add a few more
that are important for non-destructive transformations:
>
 * `WhiteSpace`
   - Can store multiple white spaces (tabs are considered white space, line
     breaks not). Important if you want to do non-destructive replacements that
     are white-space sensitive.
   - Multiple subsequent white spaces are treated as a single token.
 * `LineBreak`
 * `LineComment`
 * `BlockComment`
>
It's way easier to rebuild the JS string if the tokens already have line breaks
and comments. It's also easier to identify if previous/next/current token is a
LineBreak or Comment (sometimes needed for non-destructive transformations).

**Comment by feross** [comment]
Here's a first attempt to use `esformatter`: https://github.com/feross/standard/commit/11187a65bca014f82441df4409a1a8efdad099d5

Formats most whitespace and line breaks correctly, including these cases that @jb55 listed above:

- convert " to ' except when " contains a '
- spaced infix operators

Sidenote: what do you all think of `standard format` or `standard --format` calling into this module?

**Comment by jb55** [comment]
It all depends if you want to maintain it in `standard`. If you don't, we can move it over here. Otherwise we can keep it in standard and deprecate this project. Up to you.

**Comment by feross** [comment]
Let's move it here.

**Comment by jb55** [comment]
Alright I've moved it over in 3dba6f8a, lots of tests are still failing though, much more work to do.

**Comment by feross** [comment]
Okay, not going to add a `standard --format` command. I'll just direct people to install `standard-format` in the README :)

**Comment by feross** [comment]
Btw, if someone wants to send a PR to add `standard --format` and make it just call into `standard-format`, I'd accept it. I don't have any objections to the idea. Just don't think it's that important. :)

**Comment by Flet** [comment]
hot PR incoming
